/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HodDetailsService } from "../hodDetails.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HodDetailsCreateInput } from "./HodDetailsCreateInput";
import { HodDetails } from "./HodDetails";
import { Request } from "../../request/base/Request";
import { HodDetailsFindManyArgs } from "./HodDetailsFindManyArgs";
import { HodDetailsWhereUniqueInput } from "./HodDetailsWhereUniqueInput";
import { HodDetailsUpdateInput } from "./HodDetailsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HodDetailsControllerBase {
  constructor(
    protected readonly service: HodDetailsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HodDetails })
  @nestAccessControl.UseRoles({
    resource: "HodDetails",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHodDetails(
    @common.Body() data: HodDetailsCreateInput
  ): Promise<HodDetails> {
    return await this.service.createHodDetails({
      data: data,
      select: {
        createdAt: true,
        department: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HodDetails] })
  @ApiNestedQuery(HodDetailsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HodDetails",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hodDetailsItems(@common.Req() request: Request): Promise<HodDetails[]> {
    const args = plainToClass(HodDetailsFindManyArgs, request.query);
    return this.service.hodDetailsItems({
      ...args,
      select: {
        createdAt: true,
        department: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HodDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HodDetails",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hodDetails(
    @common.Param() params: HodDetailsWhereUniqueInput
  ): Promise<HodDetails | null> {
    const result = await this.service.hodDetails({
      where: params,
      select: {
        createdAt: true,
        department: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HodDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HodDetails",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHodDetails(
    @common.Param() params: HodDetailsWhereUniqueInput,
    @common.Body() data: HodDetailsUpdateInput
  ): Promise<HodDetails | null> {
    try {
      return await this.service.updateHodDetails({
        where: params,
        data: data,
        select: {
          createdAt: true,
          department: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HodDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HodDetails",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHodDetails(
    @common.Param() params: HodDetailsWhereUniqueInput
  ): Promise<HodDetails | null> {
    try {
      return await this.service.deleteHodDetails({
        where: params,
        select: {
          createdAt: true,
          department: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
